$axure.loadCurrentPage({
  "url":"pretest_game_2.html",
  "generationDate":new Date(1486582449015.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78a3207c68f245e28a4ac0230b25e7c2",
    "type":"Axure:Page",
    "name":"Pretest Game 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ded3c21a51a40c680d435b00f6afb21",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"b6db3e1467e54d35898d6ac254466064",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":103},
            "size":{
              "width":240,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6a292123fe44ecad13d78d3435e7de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":103},
                "size":{
                  "width":240,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76b1116d4c7548149370791caa201400",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":140},
            "size":{
              "width":1000,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae9375e9f0047d2b1fdf96eb162dbb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":140},
                "size":{
                  "width":1000,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u5.png"}},
{
          "id":"9917f71590694601b12f28f07cfcc43c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":610},
            "size":{
              "width":100,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74cd33377a0849ce983a21bfa46daaef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":610},
                "size":{
                  "width":100,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Pretest Game 3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"pretest_game_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pretest_game/u9.png"}},
{
          "id":"bbb2f9d21cb24d8c9e427ed87d79e56f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":510},
            "size":{
              "width":680,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2294355097f34f5a9c87bed9afc3ca67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":510},
                "size":{
                  "width":680,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u9.png"}},
{
          "id":"7439d4f237f140a9ae944e035863999c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":240},
            "size":{
              "width":115,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50cffe1ee0974d47a80cdf2d58606586",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":240},
                "size":{
                  "width":115,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u11.png"}},
{
          "id":"ee05d0c8b4f744aaa1668d86333bee5a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":300},
            "size":{
              "width":115,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65ff290f407044deb80ec79fdd762d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":300},
                "size":{
                  "width":115,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u11.png"}},
{
          "id":"0c8c0fc98d724aae991d395d191a9856",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":525},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1349c7c9dbba4f4eb6494ecc599bc635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":525},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u15.png"}},
{
          "id":"e267182300354e1db1213566cdd08dda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":614,
              "y":525},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5df56062b1a24535a5ef90ed13adeea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":614,
                  "y":525},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u15.png"}},
{
          "id":"130fefdd10054df78deb913a629e89b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":747,
              "y":525},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39af48c8889f416f80d677707720b05c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":747,
                  "y":525},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u15.png"}},
{
          "id":"a7006c3cd37e41e5b6e3d764af4fb310",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":881,
              "y":525},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bd9ba24b5044ebe87d828605de3da2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":881,
                  "y":525},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u15.png"}},
{
          "id":"7aa9eee055c849ddb796b4cd9b1e6935",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1015,
              "y":525},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1a30e61190a46f8ab869f9bc6eb16fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1015,
                  "y":525},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game_2/u15.png"}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}}]}}},
  "objectPaths":{
    "8ded3c21a51a40c680d435b00f6afb21":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"}},
    "b6db3e1467e54d35898d6ac254466064":{
      "scriptId":"u3"},
    "5b6a292123fe44ecad13d78d3435e7de":{
      "scriptId":"u4"},
    "76b1116d4c7548149370791caa201400":{
      "scriptId":"u5"},
    "8ae9375e9f0047d2b1fdf96eb162dbb7":{
      "scriptId":"u6"},
    "9917f71590694601b12f28f07cfcc43c":{
      "scriptId":"u7"},
    "74cd33377a0849ce983a21bfa46daaef":{
      "scriptId":"u8"},
    "bbb2f9d21cb24d8c9e427ed87d79e56f":{
      "scriptId":"u9"},
    "2294355097f34f5a9c87bed9afc3ca67":{
      "scriptId":"u10"},
    "7439d4f237f140a9ae944e035863999c":{
      "scriptId":"u11"},
    "50cffe1ee0974d47a80cdf2d58606586":{
      "scriptId":"u12"},
    "ee05d0c8b4f744aaa1668d86333bee5a":{
      "scriptId":"u13"},
    "65ff290f407044deb80ec79fdd762d0c":{
      "scriptId":"u14"},
    "0c8c0fc98d724aae991d395d191a9856":{
      "scriptId":"u15"},
    "1349c7c9dbba4f4eb6494ecc599bc635":{
      "scriptId":"u16"},
    "e267182300354e1db1213566cdd08dda":{
      "scriptId":"u17"},
    "5df56062b1a24535a5ef90ed13adeea2":{
      "scriptId":"u18"},
    "130fefdd10054df78deb913a629e89b4":{
      "scriptId":"u19"},
    "39af48c8889f416f80d677707720b05c":{
      "scriptId":"u20"},
    "a7006c3cd37e41e5b6e3d764af4fb310":{
      "scriptId":"u21"},
    "8bd9ba24b5044ebe87d828605de3da2b":{
      "scriptId":"u22"},
    "7aa9eee055c849ddb796b4cd9b1e6935":{
      "scriptId":"u23"},
    "d1a30e61190a46f8ab869f9bc6eb16fc":{
      "scriptId":"u24"}}});