$axure.loadCurrentPage({
  "url":"journey_game.html",
  "generationDate":new Date(1486577334039.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fef6d81a404a4d5c8026bcb0ad9c3f3b",
    "type":"Axure:Page",
    "name":"Journey Game",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"26c21784148549d1b3c947313f976e5e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"082f6312e6fd4e0ea2f146dc5bcd4833",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":200},
            "size":{
              "width":1020,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e7ca4e5d3a4670aee5deae194d0601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":200},
                "size":{
                  "width":1020,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/journey_game/u3.png"}},
{
          "id":"2cb6c9108e8d49478a13afe137da08ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":295},
            "size":{
              "width":105,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd367c38420343c292a79e400021affc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":295},
                "size":{
                  "width":105,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/journey_game/u5.png"}},
{
          "id":"d18acfd6a9884bc294cef48eb9582111",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":609.5,
              "y":113},
            "size":{
              "width":221,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dfbefb1e4b04e048cf57fe060821f97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":609.5,
                  "y":113},
                "size":{
                  "width":221,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}}]}}},
  "objectPaths":{
    "26c21784148549d1b3c947313f976e5e":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"}},
    "082f6312e6fd4e0ea2f146dc5bcd4833":{
      "scriptId":"u3"},
    "21e7ca4e5d3a4670aee5deae194d0601":{
      "scriptId":"u4"},
    "2cb6c9108e8d49478a13afe137da08ba":{
      "scriptId":"u5"},
    "dd367c38420343c292a79e400021affc":{
      "scriptId":"u6"},
    "d18acfd6a9884bc294cef48eb9582111":{
      "scriptId":"u7"},
    "7dfbefb1e4b04e048cf57fe060821f97":{
      "scriptId":"u8"}}});