$axure.loadCurrentPage({
  "url":"pretest_game.html",
  "generationDate":new Date(1486585392892.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"75cbe2d73e0a4b29ab79c9520a5a1057",
    "type":"Axure:Page",
    "name":"Pretest Game",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ded3c21a51a40c680d435b00f6afb21",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"ca57ab9052fa4da684bcb46abdb4b08f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":203},
            "size":{
              "width":140,
              "height":227}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a23ca06f7c454228a3c20d9b099ed9fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":203},
                "size":{
                  "width":140,
                  "height":227}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game/u8.png"}},
{
          "id":"b6db3e1467e54d35898d6ac254466064",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":103},
            "size":{
              "width":240,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6a292123fe44ecad13d78d3435e7de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":103},
                "size":{
                  "width":240,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b40e93e4c8c4f388674c3025cb18b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":260},
            "size":{
              "width":590,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a350cbf4da8847dd8b68759af7d3bb71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":260},
                "size":{
                  "width":590,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9917f71590694601b12f28f07cfcc43c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":360},
            "size":{
              "width":100,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74cd33377a0849ce983a21bfa46daaef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":360},
                "size":{
                  "width":100,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Pretest Game 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"pretest_game_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pretest_game/u14.png"}},
{
          "id":"af884c3128f5444daa7ee1f34e908447",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":223},
            "size":{
              "width":701,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ebfa0070e8a414380c11e1422f59032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":223},
                "size":{
                  "width":701,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}},
{
            "id":"0e65713a38ca4d4abe61065c1afa1ad1",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Italic', 'Arial'",
              "fontStyle":"italic",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":870,
                "y":66},
              "size":{
                "width":360,
                "height":19}},
            "adaptiveStyles":{
}},
{
            "id":"8fdf35130e8144c6a10d6ab82fa5b4f1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":50},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b143faa4e96e4a7f9c4a50c3104b912a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":50},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u4.png"}},
{
            "id":"3e64daa70e2448d19be66dce758bfd91",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Italic', 'Arial'",
              "fontStyle":"italic",
              "location":{
                "x":250,
                "y":56},
              "size":{
                "width":106,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e45d092069047f1b03898a96050b2bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Italic', 'Arial'",
                  "fontStyle":"italic",
                  "location":{
                    "x":250,
                    "y":56},
                  "size":{
                    "width":106,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8ded3c21a51a40c680d435b00f6afb21":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"},
      "0e65713a38ca4d4abe61065c1afa1ad1":{
        "scriptId":"u3"},
      "8fdf35130e8144c6a10d6ab82fa5b4f1":{
        "scriptId":"u4"},
      "b143faa4e96e4a7f9c4a50c3104b912a":{
        "scriptId":"u5"},
      "3e64daa70e2448d19be66dce758bfd91":{
        "scriptId":"u6"},
      "1e45d092069047f1b03898a96050b2bf":{
        "scriptId":"u7"}},
    "ca57ab9052fa4da684bcb46abdb4b08f":{
      "scriptId":"u8"},
    "a23ca06f7c454228a3c20d9b099ed9fe":{
      "scriptId":"u9"},
    "b6db3e1467e54d35898d6ac254466064":{
      "scriptId":"u10"},
    "5b6a292123fe44ecad13d78d3435e7de":{
      "scriptId":"u11"},
    "3b40e93e4c8c4f388674c3025cb18b6c":{
      "scriptId":"u12"},
    "a350cbf4da8847dd8b68759af7d3bb71":{
      "scriptId":"u13"},
    "9917f71590694601b12f28f07cfcc43c":{
      "scriptId":"u14"},
    "74cd33377a0849ce983a21bfa46daaef":{
      "scriptId":"u15"},
    "af884c3128f5444daa7ee1f34e908447":{
      "scriptId":"u16"},
    "3ebfa0070e8a414380c11e1422f59032":{
      "scriptId":"u17"}}});