$axure.loadCurrentPage({
  "url":"pretest_game.html",
  "generationDate":new Date(1486577333634.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"75cbe2d73e0a4b29ab79c9520a5a1057",
    "type":"Axure:Page",
    "name":"Pretest Game",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ded3c21a51a40c680d435b00f6afb21",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"ca57ab9052fa4da684bcb46abdb4b08f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":160},
            "size":{
              "width":210,
              "height":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a23ca06f7c454228a3c20d9b099ed9fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":160},
                "size":{
                  "width":210,
                  "height":340}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pretest_game/u3.png"}},
{
          "id":"b6db3e1467e54d35898d6ac254466064",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":83},
            "size":{
              "width":110,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6a292123fe44ecad13d78d3435e7de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":83},
                "size":{
                  "width":110,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b40e93e4c8c4f388674c3025cb18b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":556},
            "size":{
              "width":590,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a350cbf4da8847dd8b68759af7d3bb71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":556},
                "size":{
                  "width":590,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}}]}}},
  "objectPaths":{
    "8ded3c21a51a40c680d435b00f6afb21":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"}},
    "ca57ab9052fa4da684bcb46abdb4b08f":{
      "scriptId":"u3"},
    "a23ca06f7c454228a3c20d9b099ed9fe":{
      "scriptId":"u4"},
    "b6db3e1467e54d35898d6ac254466064":{
      "scriptId":"u5"},
    "5b6a292123fe44ecad13d78d3435e7de":{
      "scriptId":"u6"},
    "3b40e93e4c8c4f388674c3025cb18b6c":{
      "scriptId":"u7"},
    "a350cbf4da8847dd8b68759af7d3bb71":{
      "scriptId":"u8"}}});