$axure.loadCurrentPage({
  "url":"test_confirm.html",
  "generationDate":new Date(1486582449338.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e0870eb8636a4ddc98b1cf97a351aef6",
    "type":"Axure:Page",
    "name":"Test Confirm",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9bda97e731c045cc9fe4fae097c2ee12",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"23ca95d7c4b44e489405c4919ae49bf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":216},
            "size":{
              "width":240,
              "height":514}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0eec55f3e2453881e049f86d943d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":216},
                "size":{
                  "width":240,
                  "height":514}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/test_confirm/u3.png"}},
{
          "id":"6be78c4a8a1b4f198b240d2690986745",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":83},
            "size":{
              "width":157,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ef815a55f6468d863300aea9a296a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":83},
                "size":{
                  "width":157,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"663a4c1d40eb4048a2ea8164c42f6c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1020,
              "y":401},
            "size":{
              "width":222,
              "height":49},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3c57cbf8b934075abbe97297516777f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1020,
                  "y":401},
                "size":{
                  "width":222,
                  "height":49},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open My Journey in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"my_journey.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/test_confirm/u7.png"}},
{
          "id":"aec9aa8aa8cc492d92f14efceed58a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":613,
              "y":143},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81646deea22144afa9364a268606a4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":613,
                  "y":143},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a791ae499c847d5904f09a8d1327ffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":216},
            "size":{
              "width":478,
              "height":514}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1baf42372a4e569b9ce920613a24e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":216},
                "size":{
                  "width":478,
                  "height":514}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/test_confirm/u11.png"}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}}]}}},
  "objectPaths":{
    "9bda97e731c045cc9fe4fae097c2ee12":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"}},
    "23ca95d7c4b44e489405c4919ae49bf0":{
      "scriptId":"u3"},
    "bb0eec55f3e2453881e049f86d943d0b":{
      "scriptId":"u4"},
    "6be78c4a8a1b4f198b240d2690986745":{
      "scriptId":"u5"},
    "57ef815a55f6468d863300aea9a296a0":{
      "scriptId":"u6"},
    "663a4c1d40eb4048a2ea8164c42f6c30":{
      "scriptId":"u7"},
    "a3c57cbf8b934075abbe97297516777f":{
      "scriptId":"u8"},
    "aec9aa8aa8cc492d92f14efceed58a2a":{
      "scriptId":"u9"},
    "81646deea22144afa9364a268606a4a3":{
      "scriptId":"u10"},
    "0a791ae499c847d5904f09a8d1327ffc":{
      "scriptId":"u11"},
    "4e1baf42372a4e569b9ce920613a24e5":{
      "scriptId":"u12"}}});