$axure.loadCurrentPage({
  "url":"my_journey.html",
  "generationDate":new Date(1486577333878.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ab95c4db48c04e11a893f026f4c1ee16",
    "type":"Axure:Page",
    "name":"My Journey",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2d4fc115d685473bb483f5038fe20794",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"d3b9b7a84b40480494b1282445ef8bc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":160},
            "size":{
              "width":995,
              "height":530},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1cc416b2230435fab9b95f38c5d8319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":160},
                "size":{
                  "width":995,
                  "height":530},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/start_your_journey/u5.png"}},
{
          "id":"2acba5148471497e97be1a0229e6f6b4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":1025,
              "y":100.5},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2641be6467744409af269ad007179157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":1025,
                  "y":100.5},
                "size":{
                  "width":210,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"cbf74f97e7a943ff90c80bc076c87f53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":93},
            "size":{
              "width":176,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fb57efe82ff4a878a383f369e4f2c4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":93},
                "size":{
                  "width":176,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}}]}}},
  "objectPaths":{
    "2d4fc115d685473bb483f5038fe20794":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"}},
    "d3b9b7a84b40480494b1282445ef8bc9":{
      "scriptId":"u3"},
    "b1cc416b2230435fab9b95f38c5d8319":{
      "scriptId":"u4"},
    "2acba5148471497e97be1a0229e6f6b4":{
      "scriptId":"u5"},
    "2641be6467744409af269ad007179157":{
      "scriptId":"u6"},
    "cbf74f97e7a943ff90c80bc076c87f53":{
      "scriptId":"u7"},
    "7fb57efe82ff4a878a383f369e4f2c4c":{
      "scriptId":"u8"}}});