$axure.loadCurrentPage({
  "url":"name_and_appearance.html",
  "generationDate":new Date(1486585392559.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"85cc5b757c164208956c621802646610",
    "type":"Axure:Page",
    "name":"Name and Appearance",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"14e5da486ebc45a5b8507a6cee283d14",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"2b6ac5b9061046788505a4ff7d7712cd"},
{
          "id":"679fcafd12744122b1eeb94388380a28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":570,
              "y":205},
            "size":{
              "width":300,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b95133c183d04adf9df70605d91f14d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":570,
                  "y":205},
                "size":{
                  "width":300,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/name_and_appearance/u8.png"}},
{
          "id":"551c8878da9442abbab4cb8e41d5cfed",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":282},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a718cfbdd02b4889a78740ad6ac33856",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":685},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78ac59043db5400ba635c5ae4c9fc294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":685},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"62fe7d3d1748401cb711662b32a0694e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":724},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c3d85b59eb5429db61930ea041501ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":724},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"cf70e5f5b8264c32a7560ae517ce490a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":581,
              "y":123},
            "size":{
              "width":289,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bb11e6544c64dda996dc5e3d7eae492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":581,
                  "y":123},
                "size":{
                  "width":289,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4b0c504d86f48a598c925ee82d73804",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":240,
              "y":205},
            "size":{
              "width":113,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07c38a6d7cee4a20b1a2731441ccc0fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":240,
                  "y":205},
                "size":{
                  "width":113,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15afeca3f6b740058721992f5e502eda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":242,
              "y":222},
            "size":{
              "width":64,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"657b33f8297b4046ab70c5fe45e0431b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":242,
                  "y":222},
                "size":{
                  "width":64,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e3bba662cc94f2fbd5b81a5923a67f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":645},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c88d5c856544e32b4b5b5589637332b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":645},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Start Your Journey in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"start_your_journey.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_and_login/u10.png"}},
{
          "id":"a84df178b6044aeda927ce7587e3574b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":251},
            "size":{
              "width":280,
              "height":361}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce1ba4ceb22453186b0c94dee5911c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":251},
                "size":{
                  "width":280,
                  "height":361}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/name_and_appearance/u23.png"}},
{
          "id":"fe49091f2ec94927bf8ce81c4e3987e6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":326},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ed6ca33c43de404380a401fe5c5cd6a5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":364},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"83ffde9436fe45ed9dc88c54fced26e4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":398},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d9526274e1a41dbacb992d0b3af9e36",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":434},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "2b6ac5b9061046788505a4ff7d7712cd":{
      "packageId":"2b6ac5b9061046788505a4ff7d7712cd",
      "type":"Axure:Master",
      "name":"Main Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e39fb40ab8ac46e491a33586e2ec04ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":30},
              "size":{
                "width":1080,
                "height":690}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e9120404df27457692f8d36c1af90987",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":30},
                  "size":{
                    "width":1080,
                    "height":690}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u1.png"}},
{
            "id":"0e65713a38ca4d4abe61065c1afa1ad1",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Italic', 'Arial'",
              "fontStyle":"italic",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":870,
                "y":66},
              "size":{
                "width":360,
                "height":19}},
            "adaptiveStyles":{
}},
{
            "id":"8fdf35130e8144c6a10d6ab82fa5b4f1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":50},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b143faa4e96e4a7f9c4a50c3104b912a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":50},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_and_login/u4.png"}},
{
            "id":"3e64daa70e2448d19be66dce758bfd91",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Italic', 'Arial'",
              "fontStyle":"italic",
              "location":{
                "x":250,
                "y":56},
              "size":{
                "width":106,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e45d092069047f1b03898a96050b2bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Italic', 'Arial'",
                  "fontStyle":"italic",
                  "location":{
                    "x":250,
                    "y":56},
                  "size":{
                    "width":106,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "14e5da486ebc45a5b8507a6cee283d14":{
      "scriptId":"u0",
      "e39fb40ab8ac46e491a33586e2ec04ca":{
        "scriptId":"u1"},
      "e9120404df27457692f8d36c1af90987":{
        "scriptId":"u2"},
      "0e65713a38ca4d4abe61065c1afa1ad1":{
        "scriptId":"u3"},
      "8fdf35130e8144c6a10d6ab82fa5b4f1":{
        "scriptId":"u4"},
      "b143faa4e96e4a7f9c4a50c3104b912a":{
        "scriptId":"u5"},
      "3e64daa70e2448d19be66dce758bfd91":{
        "scriptId":"u6"},
      "1e45d092069047f1b03898a96050b2bf":{
        "scriptId":"u7"}},
    "679fcafd12744122b1eeb94388380a28":{
      "scriptId":"u8"},
    "b95133c183d04adf9df70605d91f14d5":{
      "scriptId":"u9"},
    "551c8878da9442abbab4cb8e41d5cfed":{
      "scriptId":"u10"},
    "a718cfbdd02b4889a78740ad6ac33856":{
      "scriptId":"u11"},
    "78ac59043db5400ba635c5ae4c9fc294":{
      "scriptId":"u12"},
    "62fe7d3d1748401cb711662b32a0694e":{
      "scriptId":"u13"},
    "9c3d85b59eb5429db61930ea041501ba":{
      "scriptId":"u14"},
    "cf70e5f5b8264c32a7560ae517ce490a":{
      "scriptId":"u15"},
    "5bb11e6544c64dda996dc5e3d7eae492":{
      "scriptId":"u16"},
    "e4b0c504d86f48a598c925ee82d73804":{
      "scriptId":"u17"},
    "07c38a6d7cee4a20b1a2731441ccc0fa":{
      "scriptId":"u18"},
    "15afeca3f6b740058721992f5e502eda":{
      "scriptId":"u19"},
    "657b33f8297b4046ab70c5fe45e0431b":{
      "scriptId":"u20"},
    "5e3bba662cc94f2fbd5b81a5923a67f9":{
      "scriptId":"u21"},
    "4c88d5c856544e32b4b5b5589637332b":{
      "scriptId":"u22"},
    "a84df178b6044aeda927ce7587e3574b":{
      "scriptId":"u23"},
    "0ce1ba4ceb22453186b0c94dee5911c2":{
      "scriptId":"u24"},
    "fe49091f2ec94927bf8ce81c4e3987e6":{
      "scriptId":"u25"},
    "ed6ca33c43de404380a401fe5c5cd6a5":{
      "scriptId":"u26"},
    "83ffde9436fe45ed9dc88c54fced26e4":{
      "scriptId":"u27"},
    "4d9526274e1a41dbacb992d0b3af9e36":{
      "scriptId":"u28"}}});